### ISSUE TITLE
怎么不用 record

### ISSUE THREAD

**Issue by ice1000** [chuigda/xjbutil4j#1]
https://github.com/chuigda/xjbutil4j/blob/5a32012c2d9806b8a26f7c3cd25083a4e64f91b3/src/main/java/tech/icey/xjbutil/container/Tuple3.java#L5

**Comment by chuigda** [comment]
Did you see the `set` functions? Yes this `Tuple` is not immutable.

**Comment by ice1000** [comment]
icic
